# Generated by Django 2.1.2 on 2018-11-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('book_title', models.TextField(max_length=100)),
                ('book_total_pages', models.IntegerField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
