# Generated by Django 2.1.2 on 2018-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
