# Generated by Django 2.1.2 on 2018-11-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_logpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpages',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserBooks'),
        ),
    ]
