# Generated by Django 2.1.2 on 2018-11-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181115_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpages',
            name='book_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Books'),
        ),
    ]
