# Generated by Django 2.1.2 on 2018-11-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181115_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbooks',
            old_name='book_title',
            new_name='books',
        ),
    ]
