# Generated by Django 2.1.2 on 2018-11-15 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181115_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbooks', to='main.Books'),
        ),
    ]
