# Generated by Django 2.1.2 on 2018-11-15 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181115_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpages',
            name='book_title',
        ),
        migrations.AddField(
            model_name='logpages',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.Books'),
        ),
    ]
