# Generated by Django 2.1.2 on 2018-11-16 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181115_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpages',
            name='books',
        ),
        migrations.AddField(
            model_name='logpages',
            name='userbooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='main.UserBooks'),
        ),
    ]
