# Generated by Django 2.1.2 on 2018-12-11 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20181211_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('-created',), 'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='logpages',
            options={'verbose_name': 'LogPages', 'verbose_name_plural': 'LogPages'},
        ),
        migrations.AlterModelOptions(
            name='userbooks',
            options={'verbose_name': 'UserBooks', 'verbose_name_plural': 'UserBooks'},
        ),
    ]
